In [ ]:
import pandas as pd
df=pd.read_csv('/content/hr_employee_dataset.csv')
df.head()

,Employee_ID,Name,Age,Gender,City,Education,Department,Job_Title,Join_Date,Years_at_Company,Salary_INR,Performance_Rating,Leaves_Taken,Employment_Status
0,EMP0001,Arjun Rao,36,Male,Hyderabad,Master's,Marketing,Content Strategist,2023-04-05,1,NaN,Excellent,1,Resigned
1,EMP0002,Sanjay Rajan,48,Male,Pune,Master's,Operations,Logistics Coordinator,2020-01-14,4,72900.0,Excellent,13,Active
2,EMP0003,Divya Sharma,44,Female,Chennai,PhD,HR,HR Executive,2021-10-08,3,49100.0,Poor,29,Resigned
3,EMP0004,Nithya Rajan,24,Female,Hyderabad,Master's,Operations,Operations Analyst,2023-09-02,1,49600.0,Good,8,Active
4,EMP0005,Rajesh Iyer,26,Male,Hyderabad,Master's,Sales,Account Manager,2020-12-27,4,86800.0,Good,8,Active

In [ ]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'City', 'Education',
       'Department', 'Job_Title', 'Join_Date', 'Years_at_Company',
       'Salary_INR', 'Performance_Rating', 'Leaves_Taken',
       'Employment_Status'],
      dtype='object')

In [ ]:
df.shape

(1000, 14)

In [ ]:
df.isnull().sum()

Employee_ID            0
Name                   0
Age                    0
Gender                 0
City                   0
Education              0
Department             0
Job_Title              0
Join_Date              0
Years_at_Company       0
Salary_INR            32
Performance_Rating    19
Leaves_Taken           0
Employment_Status      0
dtype: int64

In [ ]:
df.dtypes

Employee_ID            object
Name                   object
Age                     int64
Gender                 object
City                   object
Education              object
Department             object
Job_Title              object
Join_Date              object
Years_at_Company        int64
Salary_INR            float64
Performance_Rating     object
Leaves_Taken            int64
Employment_Status      object
dtype: object

In [ ]:
df['Performance_Rating'].value_counts(dropna=False)

Performance_Rating
Excellent    257
Good         247
Average      242
Poor         235
NaN           19
Name: count, dtype: int64

In [ ]:
df['Salary_INR'].describe()

count       968.000000
mean      72045.971074
std       26182.692490
min       28900.000000
25%       52100.000000
50%       67250.000000
75%       85950.000000
max      160400.000000
Name: Salary_INR, dtype: float64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Employee_ID'].nunique()

1000

In [ ]:
df['Join_Date'].head(10)

0    2023-04-05
1    2020-01-14
2    2021-10-08
3    2023-09-02
4    2020-12-27
5    2018-07-16
6    2016-07-25
7    2016-09-18
8    2016-04-01
9    2016-09-18
Name: Join_Date, dtype: object

In [ ]:
print("Gender:")
print(df['Gender'].value_counts(dropna=False))
print("\nCity:")
print(df['City'].value_counts(dropna=False))
print("\nDepartment:")
print(df['Department'].value_counts(dropna=False))
print("\nEmployment Status:")
print(df['Employment_Status'].value_counts(dropna=False))

Gender:
Gender
Female    520
Male      480
Name: count, dtype: int64

City:
City
Mumbai       162
Hyderabad    155
Chennai      146
Delhi        144
Kolkata      137
Pune         135
Bangalore    121
Name: count, dtype: int64

Department:
Department
Operations          174
Finance             157
Customer Support    146
Engineering         141
Sales               136
Marketing           132
HR                  114
Name: count, dtype: int64

Employment Status:
Employment_Status
Active        649
Terminated    184
Resigned      167
Name: count, dtype: int64

In [ ]:
df['Join_Date']=pd.to_datetime(df['Join_Date'])
df.dtypes

Employee_ID                   object
Name                          object
Age                            int64
Gender                        object
City                          object
Education                     object
Department                    object
Job_Title                     object
Join_Date             datetime64[ns]
Years_at_Company               int64
Salary_INR                   float64
Performance_Rating            object
Leaves_Taken                   int64
Employment_Status             object
dtype: object

In [ ]:
df['Years_at_Company'].describe()

count    1000.000000
mean        4.899000
std         2.593362
min         1.000000
25%         3.000000
50%         5.000000
75%         7.000000
max        10.000000
Name: Years_at_Company, dtype: float64

In [ ]:
df['Age'].describe()

count    1000.000000
mean       38.543000
std         9.793981
min        22.000000
25%        30.000000
50%        38.000000
75%        47.000000
max        55.000000
Name: Age, dtype: float64

In [ ]:
df['Leaves_Taken'].describe()

count    1000.000000
mean       15.154000
std         8.708853
min         0.000000
25%         8.000000
50%        15.000000
75%        23.000000
max        30.000000
Name: Leaves_Taken, dtype: float64

In [ ]:
print("Education:")
print(df['Education'].value_counts(dropna=False))
print("\nJob Title:")
print(df['Job_Title'].value_counts(dropna=False))

Education:
Education
Diploma       277
PhD           258
Bachelor's    234
Master's      231
Name: count, dtype: int64

Job Title:
Job_Title
Logistics Coordinator       63
Customer Success Manager    62
Operations Manager          60
Operations Analyst          51
Accountant                  48
Support Agent               43
Finance Manager             42
Sales Manager               42
Support Lead                41
SEO Specialist              38
Auditor                     35
Marketing Analyst           34
Account Manager             34
Sales Executive             33
Recruiter                   33
Financial Analyst           32
Content Strategist          32
DevOps Engineer             31
Senior Engineer             31
HR Manager                  31
Software Engineer           29
Payroll Specialist          29
Marketing Manager           28
Tech Lead                   27
Business Development Rep    27
QA Engineer                 23
HR Executive                21
Name: count, dtype: int64

In [ ]:
print("Salary below 0:")
print((df['Salary_INR'] < 0).sum())
print("\nSalary equal to 0:")
print((df['Salary_INR'] == 0).sum())
print("\nLowest 10 salaries:")
print(df['Salary_INR'].nsmallest(10))
print("\nHighest 10 salaries:")
print(df['Salary_INR'].nlargest(10))

Salary below 0:
0

Salary equal to 0:
0

Lowest 10 salaries:
681    28900.0
791    29600.0
321    30000.0
556    30100.0
564    31100.0
343    31600.0
875    31700.0
15     32200.0
40     32700.0
857    32700.0
Name: Salary_INR, dtype: float64

Highest 10 salaries:
21     160400.0
467    159300.0
309    158300.0
83     158100.0
465    156100.0
502    154900.0
135    154100.0
815    154100.0
953    154100.0
471    153700.0
Name: Salary_INR, dtype: float64

In [ ]:
print("Age values outside 18–60:")
print(df[(df['Age'] < 18) | (df['Age'] > 60)][['Employee_ID', 'Age']])
print("\nYears at Company outside 0–50:")
print(df[(df['Years_at_Company'] < 0) | (df['Years_at_Company'] > 50)][['Employee_ID', 'Years_at_Company']])
print("\nLeaves outside 0–30:")
print(df[(df['Leaves_Taken'] < 0) | (df['Leaves_Taken'] > 30)][['Employee_ID', 'Leaves_Taken']])

Age values outside 18–60:
Empty DataFrame
Columns: [Employee_ID, Age]
Index: []

Years at Company outside 0–50:
Empty DataFrame
Columns: [Employee_ID, Years_at_Company]
Index: []

Leaves outside 0–30:
Empty DataFrame
Columns: [Employee_ID, Leaves_Taken]
Index: []

In [ ]:
from datetime import datetime
current_date = pd.Timestamp.today()
df['Calculated_Years'] = (
    (current_date - df['Join_Date']).dt.days / 365.25
)
df[['Join_Date', 'Years_at_Company', 'Calculated_Years']].head(10)

   Join_Date  Years_at_Company  Calculated_Years
0 2023-04-05                 1          3.433265
1 2020-01-14                 4          6.655715
2 2021-10-08                 3          4.922656
3 2023-09-02                 1          3.022587
4 2020-12-27                 4          5.702943
5 2018-07-16                 6          8.153320
6 2016-07-25                 8         10.127310
7 2016-09-18                 8          9.976728
8 2016-04-01                 8         10.442163
9 2016-09-18                 8          9.976728

In [ ]:
df.drop(columns=['Calculated_Years'], inplace=True)
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'City', 'Education',
       'Department', 'Job_Title', 'Join_Date', 'Years_at_Company',
       'Salary_INR', 'Performance_Rating', 'Leaves_Taken',
       'Employment_Status'],
      dtype='object')

In [ ]:
missing_salary = df[df['Salary_INR'].isnull()]
missing_performance = df[df['Performance_Rating'].isnull()]
print("Rows with missing Salary:")
display(missing_salary)
print("\nRows with missing Performance Rating:")
display(missing_performance)

Rows with missing Salary:

,Employee_ID,Name,Age,Gender,City,Education,Department,Job_Title,Join_Date,Years_at_Company,Salary_INR,Performance_Rating,Leaves_Taken,Employment_Status
0,EMP0001,Arjun Rao,36,Male,Hyderabad,Master's,Marketing,Content Strategist,2023-04-05,1,NaN,Excellent,1,Resigned
9,EMP0010,Sanjay Menon,54,Male,Bangalore,Master's,Engineering,DevOps Engineer,2016-09-18,8,NaN,Excellent,15,Resigned
82,EMP0083,Rajesh Verma,39,Male,Pune,Master's,Sales,Sales Executive,2016-06-16,8,NaN,NaN,27,Active
171,EMP0172,Sanjay Kumar,25,Male,Pune,Bachelor's,Customer Support,Support Agent,2019-08-17,5,NaN,Good,4,Active
215,EMP0216,Rajesh Menon,46,Male,Kolkata,Diploma,Marketing,Content Strategist,2019-02-05,5,NaN,Good,2,Active
235,EMP0236,Arun Verma,52,Male,Bangalore,Diploma,Operations,Operations Manager,2018-11-10,6,NaN,Average,5,Active
278,EMP0279,Rajesh Rao,32,Male,Mumbai,Bachelor's,HR,HR Manager,2021-02-23,3,NaN,Poor,0,Active
307,EMP0308,Siddharth Nair,50,Male,Chennai,Diploma,HR,Payroll Specialist,2019-11-09,5,NaN,Poor,17,Terminated
325,EMP0326,Deepak Pillai,32,Male,Mumbai,PhD,Finance,Finance Manager,2020-02-01,4,NaN,Poor,3,Active
333,EMP0334,Divya Das,47,Female,Hyderabad,PhD,Engineering,QA Engineer,2022-12-24,2,NaN,Good,14,Terminated
334,EMP0335,Ananya Kumar,54,Female,Mumbai,Master's,Customer Support,Customer Success Manager,2021-11-24,3,NaN,Excellent,20,Active
366,EMP0367,Arjun Iyer,28,Male,Pune,Master's,Operations,Operations Analyst,2020-06-21,4,NaN,Average,6,Active
419,EMP0420,Ananya Rajan,42,Female,Bangalore,Diploma,Marketing,SEO Specialist,2022-07-11,2,NaN,Good,3,Active
459,EMP0460,Manoj Rajan,30,Male,Chennai,Bachelor's,Finance,Financial Analyst,2023-11-15,1,NaN,Excellent,0,Active
482,EMP0483,Sneha Iyer,41,Female,Bangalore,Bachelor's,HR,Recruiter,2015-04-13,9,NaN,Good,4,Active
559,EMP0560,Shreya Sharma,52,Female,Pune,Bachelor's,Marketing,Marketing Manager,2020-07-19,4,NaN,Average,13,Active
566,EMP0567,Aishwarya Bose,45,Female,Kolkata,PhD,Engineering,Senior Engineer,2016-07-18,8,NaN,Poor,24,Active
595,EMP0596,Ravi Verma,22,Male,Mumbai,Bachelor's,Customer Support,Customer Success Manager,2020-03-10,4,NaN,Poor,23,Active
598,EMP0599,Vikram Das,30,Male,Kolkata,PhD,Sales,Sales Executive,2021-05-23,3,NaN,Average,21,Active
705,EMP0706,Karthik Bose,36,Male,Mumbai,Bachelor's,Finance,Accountant,2016-06-25,8,NaN,Average,13,Active
708,EMP0709,Bhavana Das,33,Female,Chennai,PhD,Engineering,QA Engineer,2020-07-05,4,NaN,Average,21,Active
715,EMP0716,Priya Pillai,30,Female,Delhi,PhD,Sales,Account Manager,2023-11-13,1,NaN,Good,3,Active
716,EMP0717,Meera Sharma,38,Female,Pune,Master's,Operations,Logistics Coordinator,2019-07-31,5,NaN,Average,26,Active
722,EMP0723,Saranya Patel,52,Female,Delhi,Master's,Marketing,SEO Specialist,2017-09-25,7,NaN,Average,3,Terminated
745,EMP0746,Divya Pillai,38,Female,Kolkata,Bachelor's,HR,Payroll Specialist,2021-12-17,3,NaN,Good,17,Terminated
754,EMP0755,Arun Rao,46,Male,Kolkata,Master's,Finance,Accountant,2018-11-26,6,NaN,Excellent,11,Active
832,EMP0833,Nikhil Nair,44,Male,Mumbai,Bachelor's,Engineering,Tech Lead,2021-10-29,3,NaN,Average,24,Resigned
899,EMP0900,Arun Mehta,28,Male,Mumbai,Master's,Marketing,SEO Specialist,2019-01-06,5,NaN,Poor,24,Resigned
926,EMP0927,Revathi Mehta,28,Female,Mumbai,Diploma,Operations,Operations Analyst,2021-07-04,3,NaN,Poor,20,Active
935,EMP0936,Pooja Rao,31,Female,Pune,Master's,HR,HR Manager,2016-08-23,8,NaN,Poor,7,Active
959,EMP0960,Shreya Verma,49,Female,Kolkata,Bachelor's,Operations,Logistics Coordinator,2019-07-03,5,NaN,Excellent,12,Resigned
966,EMP0967,Nikhil Pillai,52,Male,Mumbai,Bachelor's,Customer Support,Support Lead,2018-01-30,6,NaN,Good,18,Active

Rows with missing Performance Rating:

,Employee_ID,Name,Age,Gender,City,Education,Department,Job_Title,Join_Date,Years_at_Company,Salary_INR,Performance_Rating,Leaves_Taken,Employment_Status
72,EMP0073,Saranya Mehta,46,Female,Kolkata,PhD,Engineering,Senior Engineer,2021-06-12,3,94600.0,NaN,21,Active
82,EMP0083,Rajesh Verma,39,Male,Pune,Master's,Sales,Sales Executive,2016-06-16,8,NaN,NaN,27,Active
207,EMP0208,Revathi Iyer,24,Female,Kolkata,Bachelor's,Operations,Operations Analyst,2022-01-08,2,84300.0,NaN,5,Active
243,EMP0244,Sneha Pillai,50,Female,Bangalore,Bachelor's,Engineering,DevOps Engineer,2017-12-22,7,84600.0,NaN,25,Active
253,EMP0254,Ravi Das,26,Male,Delhi,Bachelor's,Marketing,SEO Specialist,2019-05-09,5,78000.0,NaN,14,Active
271,EMP0272,Rahul Das,47,Male,Mumbai,Diploma,HR,Payroll Specialist,2020-05-09,4,57200.0,NaN,23,Resigned
300,EMP0301,Rahul Patel,29,Male,Mumbai,Diploma,Operations,Logistics Coordinator,2015-06-16,9,67700.0,NaN,18,Active
364,EMP0365,Ravi Pillai,37,Male,Chennai,Diploma,Sales,Sales Executive,2018-08-22,6,41000.0,NaN,12,Resigned
396,EMP0397,Aishwarya Pillai,46,Female,Chennai,Diploma,Marketing,Content Strategist,2020-04-24,4,47400.0,NaN,13,Active
404,EMP0405,Sowmya Patel,34,Female,Kolkata,Bachelor's,Engineering,Senior Engineer,2021-12-25,3,84800.0,NaN,15,Active
438,EMP0439,Suresh Mehta,54,Male,Bangalore,Bachelor's,Engineering,Senior Engineer,2023-10-16,1,87400.0,NaN,8,Resigned
497,EMP0498,Ravi Rao,41,Male,Kolkata,Master's,Sales,Sales Manager,2017-05-09,7,48200.0,NaN,25,Terminated
751,EMP0752,Sneha Rajan,52,Female,Pune,Diploma,Marketing,Marketing Manager,2021-01-02,3,82600.0,NaN,18,Active
835,EMP0836,Deepak Nair,38,Male,Kolkata,Bachelor's,Marketing,SEO Specialist,2016-05-24,8,68400.0,NaN,5,Active
858,EMP0859,Suresh Mehta,33,Male,Kolkata,Diploma,Sales,Business Development Rep,2018-03-03,6,49100.0,NaN,23,Resigned
870,EMP0871,Lakshmi Nair,36,Female,Delhi,Diploma,HR,HR Executive,2021-04-16,3,52700.0,NaN,16,Terminated
878,EMP0879,Ananya Menon,32,Female,Hyderabad,Diploma,Marketing,Content Strategist,2015-02-10,9,68000.0,NaN,2,Active
890,EMP0891,Saranya Rajan,23,Female,Pune,PhD,Operations,Logistics Coordinator,2022-07-15,2,54600.0,NaN,30,Resigned
925,EMP0926,Shreya Singh,36,Female,Kolkata,Diploma,Finance,Auditor,2020-07-19,4,105200.0,NaN,5,Active

In [ ]:
print("Salary median:", df['Salary_INR'].median())
print("Salary mean:", df['Salary_INR'].mean())
print("\nPerformance Rating:")
print(df['Performance_Rating'].value_counts())

Salary median: 67250.0
Salary mean: 72045.97107438017

Performance Rating:
Performance_Rating
Excellent    257
Good         247
Average      242
Poor         235
Name: count, dtype: int64

In [ ]:
df['Salary_INR'].fillna(df['Salary_INR'].median(), inplace=True)
df['Performance_Rating'].fillna(
    df['Performance_Rating'].mode()[0],
    inplace=True
)
df.isnull().sum()

/tmp/ipykernel_3303/2726440478.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary_INR'].fillna(df['Salary_INR'].median(), inplace=True)
/tmp/ipykernel_3303/2726440478.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Performance_Rating'].fillna(

Employee_ID           0
Name                  0
Age                   0
Gender                0
City                  0
Education             0
Department            0
Job_Title             0
Join_Date             0
Years_at_Company      0
Salary_INR            0
Performance_Rating    0
Leaves_Taken          0
Employment_Status     0
dtype: int64

In [ ]:
df['Salary_INR'] = df['Salary_INR'].fillna(df['Salary_INR'].median())
df['Performance_Rating'] = df['Performance_Rating'].fillna(
    df['Performance_Rating'].mode()[0]
)
df.isnull().sum()

Employee_ID           0
Name                  0
Age                   0
Gender                0
City                  0
Education             0
Department            0
Job_Title             0
Join_Date             0
Years_at_Company      0
Salary_INR            0
Performance_Rating    0
Leaves_Taken          0
Employment_Status     0
dtype: int64

In [ ]:
df['Employee_ID'].nunique(), len(df)

(1000, 1000)

In [ ]:
df.describe()

,Age,Join_Date,Years_at_Company,Salary_INR,Leaves_Taken
count,1000.000000,1000,1000.000000,1000.000000,1000.000000
mean,38.543000,2019-08-12 02:47:02.400000,4.899000,71892.500000,15.154000
min,22.000000,2015-01-03 00:00:00,1.000000,28900.000000,0.000000
25%,30.000000,2017-04-29 12:00:00,3.000000,52875.000000,8.000000
50%,38.000000,2019-09-06 12:00:00,5.000000,67250.000000,15.000000
75%,47.000000,2021-11-26 12:00:00,7.000000,85525.000000,23.000000
max,55.000000,2023-12-26 00:00:00,10.000000,160400.000000,30.000000
std,9.793981,NaN,2.593362,25773.776621,8.708853

In [ ]:
df['Department'].value_counts()

Department
Operations          174
Finance             157
Customer Support    146
Engineering         141
Sales               136
Marketing           132
HR                  114
Name: count, dtype: int64

In [ ]:
df.groupby('Department')['Salary_INR'].agg(['count', 'mean', 'median']).sort_values('mean', ascending=False)

                  count           mean    median
Department
Engineering         141  107484.042553  110700.0
Finance             157   80607.643312   80900.0
Sales               136   71267.279412   69250.0
Marketing           132   70286.363636   69800.0
Operations          174   63111.781609   63300.0
HR                  114   61003.947368   60850.0
Customer Support    146   49149.315068   49550.0

In [ ]:
df.groupby('Job_Title')['Salary_INR'].agg(['count', 'mean', 'median']).sort_values('mean', ascending=False)

                          count           mean    median
Job_Title
QA Engineer                  23  119978.260870  124100.0
Senior Engineer              31  109575.806452  114500.0
Tech Lead                    27  105061.111111  109800.0
DevOps Engineer              31  104198.387097  108700.0
Software Engineer            29  101106.896552   98900.0
Accountant                   48   85014.583333   89550.0
Finance Manager              42   80103.571429   77750.0
Auditor                      35   78365.714286   79300.0
Marketing Manager            28   77751.785714   79200.0
Financial Analyst            32   77110.937500   77850.0
Account Manager              34   76160.294118   76900.0
Sales Executive              33   71781.818182   69000.0
SEO Specialist               38   71225.000000   70750.0
Business Development Rep     27   69907.407407   74200.0
Sales Manager                42   67776.190476   64050.0
Marketing Analyst            34   67735.294118   67500.0
Content Strategist           32   65350.000000   67250.0
Operations Manager           60   64175.833333   64100.0
Recruiter                    33   63274.242424   65300.0
Logistics Coordinator        63   62704.761905   63100.0
Operations Analyst           51   62362.745098   59400.0
HR Executive                 21   60595.238095   58900.0
HR Manager                   31   60087.096774   63800.0
Payroll Specialist           29   59696.551724   57200.0
Customer Success Manager     62   49346.774194   47400.0
Support Lead                 41   49254.878049   51200.0
Support Agent                43   48763.953488   49800.0

In [ ]:
df.groupby('Education')['Salary_INR'].agg(['count', 'mean', 'median']).sort_values('mean', ascending=False)

            count          mean   median
Education
PhD           258  72791.472868  67275.0
Bachelor's    234  72244.658120  67250.0
Diploma       277  71385.018051  67250.0
Master's      231  71140.259740  67250.0

In [ ]:
df.groupby('City')['Salary_INR'].agg(['count', 'mean', 'median']).sort_values('mean', ascending=False)

           count          mean   median
City
Kolkata      137  72784.671533  67800.0
Hyderabad    155  72630.322581  67900.0
Chennai      146  72592.123288  67250.0
Mumbai       162  72534.876543  67250.0
Bangalore    121  72090.082645  67250.0
Pune         135  70643.703704  67250.0
Delhi        144  69822.222222  64450.0

In [ ]:
df.groupby('Employment_Status')['Salary_INR'].agg(['count', 'mean', 'median']).sort_values('mean', ascending=False)

                   count          mean   median
Employment_Status
Resigned             167  73720.059880  67300.0
Active               649  71593.451464  67250.0
Terminated           184  71288.586957  67250.0

In [ ]:
df.groupby(['Department', 'Employment_Status']).size().unstack(fill_value=0)

Employment_Status  Active  Resigned  Terminated
Department
Customer Support       93        24          29
Engineering            87        29          25
Finance               106        25          26
HR                     73        20          21
Marketing              87        25          20
Operations            119        24          31
Sales                  84        20          32

In [ ]:
department_status = df.groupby(['Department', 'Employment_Status']).size().unstack(fill_value=0)
department_status['Total'] = department_status.sum(axis=1)
department_status['Attrition_Rate'] = (
    (department_status['Resigned'] + department_status['Terminated'])
    / department_status['Total'] * 100
)
department_status.sort_values('Attrition_Rate', ascending=False)

Employment_Status  Active  Resigned  Terminated  Total  Attrition_Rate
Department
Engineering            87        29          25    141       38.297872
Sales                  84        20          32    136       38.235294
Customer Support       93        24          29    146       36.301370
HR                     73        20          21    114       35.964912
Marketing              87        25          20    132       34.090909
Finance               106        25          26    157       32.484076
Operations            119        24          31    174       31.609195

In [ ]:
performance_status = df.groupby(
    ['Performance_Rating', 'Employment_Status']
).size().unstack(fill_value=0)
performance_status['Total'] = performance_status.sum(axis=1)
performance_status['Attrition_Rate'] = (
    (performance_status['Resigned'] + performance_status['Terminated'])
    / performance_status['Total'] * 100
)
performance_status.sort_values('Attrition_Rate', ascending=False)

Employment_Status   Active  Resigned  Terminated  Total  Attrition_Rate
Performance_Rating
Average                152        43          47    242       37.190083
Good                   159        37          51    247       35.627530
Poor                   152        40          43    235       35.319149
Excellent              186        47          43    276       32.608696

In [ ]:
tenure_status = df.groupby(
    ['Years_at_Company', 'Employment_Status']
).size().unstack(fill_value=0)
tenure_status['Total'] = tenure_status.sum(axis=1)
tenure_status['Attrition_Rate'] = (
    (tenure_status['Resigned'] + tenure_status['Terminated'])
    / tenure_status['Total'] * 100
)
tenure_status

Employment_Status  Active  Resigned  Terminated  Total  Attrition_Rate
Years_at_Company
1                      77        21          18    116       33.620690
2                      86        15          23    124       30.645161
3                      66        22          23    111       40.540541
4                      74        20          17    111       33.333333
5                      68        23          24    115       40.869565
6                      66        16          19    101       34.653465
7                      67        16          14     97       30.927835
8                      88        16          24    128       31.250000
9                      57        17          22     96       40.625000
10                      0         1           0      1      100.000000

In [ ]:
df.groupby('Employment_Status')['Leaves_Taken'].agg(
    ['count', 'mean', 'median']
).sort_values('mean', ascending=False)

                   count       mean  median
Employment_Status
Resigned             167  15.598802    16.0
Terminated           184  15.500000    15.0
Active               649  14.941448    15.0

In [ ]:
df.groupby('Employment_Status')['Age'].agg(
    ['count', 'mean', 'median']
).sort_values('mean', ascending=False)

                   count       mean  median
Employment_Status
Resigned             167  39.413174    40.0
Terminated           184  38.918478    39.0
Active               649  38.212635    38.0

In [ ]:
gender_status = df.groupby(
    ['Gender', 'Employment_Status']
).size().unstack(fill_value=0)
gender_status['Total'] = gender_status.sum(axis=1)
gender_status['Attrition_Rate'] = (
    (gender_status['Resigned'] + gender_status['Terminated'])
    / gender_status['Total'] * 100
)
gender_status

Employment_Status  Active  Resigned  Terminated  Total  Attrition_Rate
Gender
Female                335        82         103    520       35.576923
Male                  314        85          81    480       34.583333

In [ ]:
city_status = df.groupby(
    ['City', 'Employment_Status']
).size().unstack(fill_value=0)
city_status['Total'] = city_status.sum(axis=1)
city_status['Attrition_Rate'] = (
    (city_status['Resigned'] + city_status['Terminated'])
    / city_status['Total'] * 100
)
city_status.sort_values('Attrition_Rate', ascending=False)

Employment_Status  Active  Resigned  Terminated  Total  Attrition_Rate
City
Delhi                  91        28          25    144       36.805556
Hyderabad              99        27          29    155       36.129032
Mumbai                104        26          32    162       35.802469
Kolkata                88        22          27    137       35.766423
Bangalore              79        17          25    121       34.710744
Chennai                97        22          27    146       33.561644
Pune                   91        25          19    135       32.592593

In [ ]:
salary_status = df.groupby('Employment_Status')['Salary_INR'].agg(
    ['count', 'mean', 'median']
)
salary_status.sort_values('mean', ascending=False)

                   count          mean   median
Employment_Status
Resigned             167  73720.059880  67300.0
Active               649  71593.451464  67250.0
Terminated           184  71288.586957  67250.0

In [ ]:
performance_salary = df.groupby('Performance_Rating')['Salary_INR'].agg(
    ['count', 'mean', 'median']
)
performance_salary.sort_values('mean', ascending=False)

                    count          mean   median
Performance_Rating
Good                  247  72992.307692  69500.0
Excellent             276  72909.601449  68400.0
Average               242  71869.214876  67250.0
Poor                  235  69565.957447  64900.0

In [ ]:
tenure_salary = df.groupby('Years_at_Company')['Salary_INR'].agg(
    ['count', 'mean', 'median']
)
tenure_salary

                  count          mean   median
Years_at_Company
1                   116  66825.431034  64300.0
2                   124  67561.290323  65400.0
3                   111  72597.297297  67300.0
4                   111  73075.225225  67250.0
5                   115  71907.826087  67250.0
6                   101  74057.920792  69500.0
7                    97  71114.948454  67100.0
8                   128  77867.578125  71600.0
9                    96  72242.187500  67750.0
10                    1  43800.000000  43800.0

In [ ]:
df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[20, 30, 40, 50, 60],
    labels=['21-30', '31-40', '41-50', '51-60']
)
age_status = df.groupby(
    ['Age_Group', 'Employment_Status'],
    observed=False
).size().unstack(fill_value=0)
age_status['Total'] = age_status.sum(axis=1)
age_status['Attrition_Rate'] = (
    (age_status['Resigned'] + age_status['Terminated'])
    / age_status['Total'] * 100
)
age_status

Employment_Status  Active  Resigned  Terminated  Total  Attrition_Rate
Age_Group
21-30                 178        41          45    264       32.575758
31-40                 197        44          58    299       34.113712
41-50                 182        53          50    285       36.140351
51-60                  92        29          31    152       39.473684

In [ ]:
age_salary = df.groupby('Age_Group', observed=False)['Salary_INR'].agg(
    ['count', 'mean', 'median']
)
age_salary

           count          mean   median
Age_Group
21-30        264  73559.469697  67850.0
31-40        299  70694.481605  66600.0
41-50        285  71144.385965  67250.0
51-60        152  72756.578947  67250.0

In [ ]:
department_performance = df.groupby(
    ['Department', 'Performance_Rating']
).size().unstack(fill_value=0)
department_performance

Performance_Rating  Average  Excellent  Good  Poor
Department
Customer Support         37         35    28    46
Engineering              33         38    42    28
Finance                  38         50    35    34
HR                       19         30    22    43
Marketing                38         36    36    22
Operations               41         50    49    34
Sales                    36         37    35    28

In [ ]:
department_performance_pct = (
    df.groupby(['Department', 'Performance_Rating'])
      .size()
      .groupby(level=0)
      .apply(lambda x: x / x.sum() * 100)
      .unstack(fill_value=0)
)
department_performance_pct

Performance_Rating                   Average  Excellent       Good       Poor
Department       Department
Customer Support Customer Support  25.342466  23.972603  19.178082  31.506849
Engineering      Engineering       23.404255  26.950355  29.787234  19.858156
Finance          Finance           24.203822  31.847134  22.292994  21.656051
HR               HR                16.666667  26.315789  19.298246  37.719298
Marketing        Marketing         28.787879  27.272727  27.272727  16.666667
Operations       Operations        23.563218  28.735632  28.160920  19.540230
Sales            Sales             26.470588  27.205882  25.735294  20.588235

In [ ]:
department_leaves = df.groupby('Department')['Leaves_Taken'].agg(
    ['count', 'mean', 'median']
).sort_values('mean', ascending=False)
department_leaves

                  count       mean  median
Department
Engineering         141  15.751773    16.0
Sales               136  15.536765    15.0
Finance             157  15.433121    16.0
Marketing           132  15.280303    16.0
HR                  114  15.070175    16.0
Customer Support    146  14.863014    15.0
Operations          174  14.321839    14.0

In [ ]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'City', 'Education',
       'Department', 'Job_Title', 'Join_Date', 'Years_at_Company',
       'Salary_INR', 'Performance_Rating', 'Leaves_Taken', 'Employment_Status',
       'Age_Group'],
      dtype='object')

In [ ]:
df.to_csv('/content/HR_Employee_Analytics_Cleaned.csv', index=False)

In [ ]:
from google.colab import files
files.download('/content/HR_Employee_Analytics_Cleaned.csv')